# Generated by Django 3.2.11 on 2022-01-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseFeePerGas', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('difficulty', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('extraData', models.TextField(blank=True, null=True)),
                ('gasLimit', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('gasUsed', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('logsBloom', models.TextField(blank=True, null=True)),
                ('miner', models.TextField(blank=True, null=True)),
                ('mixHash', models.TextField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True, unique=True)),
                ('parentHash', models.TextField(blank=True, null=True)),
                ('receiptsRoot', models.TextField(blank=True, null=True)),
                ('sha3Uncles', models.TextField(blank=True, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('stateRoot', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('totalDifficulty', models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True)),
                ('transactions', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, unique=True)),
                ('total_nfts', models.BigIntegerField(null=True)),
                ('total_Txs', models.BigIntegerField(null=True)),
                ('balance', models.TextField(null=True)),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('walletaddress', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NftCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_url', models.URLField(max_length=120, unique=True)),
                ('smartContract', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=500, null=True, unique=True)),
                ('nonc', models.IntegerField(null=True)),
                ('transaction_index', models.IntegerField(null=True)),
                ('from_address', models.CharField(max_length=120, null=True)),
                ('to_address', models.CharField(max_length=120, null=True)),
                ('value', models.CharField(max_length=120, null=True)),
                ('gas', models.IntegerField(null=True)),
                ('gas_price', models.BigIntegerField(null=True)),
                ('input', models.TextField(null=True)),
                ('receipt_cumulative_gas_used', models.IntegerField(null=True)),
                ('receipt_gas_used', models.IntegerField(null=True)),
                ('receipt_contract_address', models.CharField(max_length=120, null=True)),
                ('receipt_root', models.CharField(max_length=120, null=True)),
                ('receipt_status', models.IntegerField(null=True)),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.IntegerField(null=True)),
                ('block_hash', models.CharField(max_length=120, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csvmanager.csv')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.TextField(blank=True, null=True)),
                ('token_id', models.TextField(blank=True, null=True)),
                ('block_number_minted', models.TextField(blank=True, null=True)),
                ('owner_of', models.TextField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('token_uri', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.IntegerField(blank=True, null=True)),
                ('syncing', models.TextField(blank=True, null=True)),
                ('frozen', models.TextField(blank=True, null=True)),
                ('field_unique', models.TextField(blank=True, null=True)),
                ('nft_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='csvmanager.nftcompany')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmanager.csv')),
            ],
        ),
        migrations.AddField(
            model_name='csv',
            name='tags',
            field=models.ManyToManyField(related_name='wallet_tags', to='csvmanager.Tags'),
        ),
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nft_company', models.ManyToManyField(related_name='Nft_Company_Features', to='csvmanager.NftCompany')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_decimals', models.BigIntegerField(blank=True, null=True)),
                ('contract_name', models.TextField(blank=True, null=True)),
                ('contract_ticker_symbol', models.TextField(blank=True, null=True)),
                ('contract_address', models.CharField(max_length=120, null=True, unique=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('last_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
                ('balance_24h', models.TextField(blank=True, null=True)),
                ('quote_rate', models.TextField(blank=True, null=True)),
                ('quote_rate_24h', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('quote_24h', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmanager.csv')),
            ],
        ),
    ]
