# Generated by Django 3.2.9 on 2021-11-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='nfts',
            new_name='nft',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
