# Generated by Django 3.2.10 on 2021-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='csv',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NftCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_url', models.URLField(max_length=120)),
                ('company_features', models.ManyToManyField(to='csvmanager.CompanyFeature')),
            ],
        ),
    ]
