# Generated by Django 3.2.9 on 2021-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0002_alter_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='unique_field',
            field=models.TextField(null=True),
        ),
    ]
