# Generated by Django 3.2.10 on 2021-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0002_auto_20211228_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedata',
            name='int_balance',
            field=models.DecimalField(blank=True, decimal_places=19, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='balancedata',
            name='max_balance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='balance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='balance_24h',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='contract_decimals',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='contract_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='contract_ticker_symbol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='last_transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='quote_24h',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='quote_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='quote_rate_24h',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='block_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='block_number_minted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='contract_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='field_unique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='frozen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='is_valid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner_of',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='symbol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='syncing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
