# Generated by Django 3.2.9 on 2021-11-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0002_auto_20211123_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
