# Generated by Django 3.2.9 on 2021-12-04 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0003_alter_csv_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block_hash',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gas_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='input',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nonc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_contract_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_cumulative_gas_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_gas_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_root',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
