# Generated by Django 3.2.10 on 2021-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0003_auto_20211229_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcompany',
            name='site_url',
            field=models.URLField(max_length=120, unique=True),
        ),
    ]
