# Generated by Django 3.2.9 on 2021-12-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0003_nft_unique_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='unique_field',
            new_name='field_unique',
        ),
    ]
