# Generated by Django 3.2.9 on 2021-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0004_rename_unique_field_nft_field_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='total',
            field=models.TextField(null=True),
        ),
    ]
