# Generated by Django 3.2.9 on 2021-12-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0005_alter_transaction_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction',
        ),
    ]
