# Generated by Django 3.2.9 on 2021-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0005_nft_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='total',
        ),
        migrations.AddField(
            model_name='csv',
            name='total_nfts',
            field=models.BigIntegerField(null=True),
        ),
    ]
