# Generated by Django 3.2.9 on 2021-12-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0006_remove_transaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.BigIntegerField(null=True),
        ),
    ]
