# Generated by Django 3.2.9 on 2021-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0006_auto_20211213_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='total_Txs',
            field=models.BigIntegerField(null=True),
        ),
    ]
