# Generated by Django 3.2.9 on 2021-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0007_alter_transaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
