# Generated by Django 3.2.9 on 2021-12-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0009_alter_transaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gas_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
