# Generated by Django 3.2.9 on 2021-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0010_alter_transaction_gas_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='nft',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
