# Generated by Django 3.2.9 on 2021-12-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0011_alter_nft_nft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='nft',
            new_name='block_number',
        ),
        migrations.AddField(
            model_name='nft',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='block_number_minted',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='contract_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='frozen',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='is_valid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='metadata',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='owner_of',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='symbol',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='syncing',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_uri',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='balancedata',
            name='balance',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
