# Generated by Django 3.2.9 on 2021-12-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0012_auto_20211207_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
