# Generated by Django 3.2.9 on 2021-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0013_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='block_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='block_number_minted',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='contract_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='frozen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner_of',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='symbol',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='syncing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_uri',
            field=models.TextField(null=True),
        ),
    ]
